version: '3'

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/share/nginx/html

    ports:
      - 80:80
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 8081:8081